# Extra logging related to initialization of Log4j
# Set to debug or trace if log4j initialization is failing
status = warn
# Name of the configuration
name = PropertiesConfig

appenders = console, ivt

# Console appender configuration
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# application's appender configuration
appender.ivt.type = BufferedAppender
appender.ivt.name = applicationLogger
appender.ivt.layout.type = PatternLayout
appender.ivt.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Root logger level
rootLogger.level = info
rootLogger.appenderRef.console.ref = consoleLogger
rootLogger.appenderRef.ivt.ref = applicationLogger

#logger.validation.name = com.okworx.ilcd.validation
#logger.validation.level = warn

#logger.profile.name = com.okworx.ilcd.validation.profile
#logger.profile.level = trace

#logger.OrphansValidator.name = com.okworx.ilcd.validation.OrphansValidator
#logger.OrphansValidator.level = debug

#logger.XSLTStylesheetValidator.name = com.okworx.ilcd.validation.XSLTStylesheetValidator
#logger.XSLTStylesheetValidator.level = debug


#logger.ReferenceBuilder.name = com.okworx.ilcd.validation.reference.ReferenceBuilder
#logger.ReferenceBuilder.level = debug

#logger.ResourceResolver.name = com.okworx.ilcd.validation.util.ResourceResolver
#logger.ResourceResolver.level = trace

#logger.CURIResolver.name = com.okworx.ilcd.validation.util.CURIResolver
#logger.CURIResolver.level = trace

#logger.ReferenceListCreator.name = com.okworx.ilcd.validation.ReferenceListCreator
#logger.ReferenceListCreator.level = trace

#logger.util.name = com.okworx.ilcd.validation.tool.util
#logger.util.level = trace

#logger.LifeCycle.name = com.okworx.ilcd.validation.tool.rcp.LifeCycle
#logger.LifeCycle.level = trace
