bin.includes = META-INF/,\
               .,\
               Application.e4xmi,\
               plugin.xml,\
               resources/,\
               src/com/okworx/ilcd/validation/tool/resource/,\
               target/dependency/*,\
               splash.bmp
source.. = src/
