<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>com.okworx.ilcd.validation.tool.product</artifactId>
	<parent>
		<groupId>com.okworx.ilcd.validation</groupId>
		<artifactId>com.okworx.ilcd.validation.tool.releng</artifactId>
		<version>2.14.0</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<packaging>eclipse-repository</packaging>

	<properties>
		<sign.macos.skip>true</sign.macos.skip>
		<sign.gpg.skip>true</sign.gpg.skip>
		<dmg.skip>true</dmg.skip>
	</properties>
	
	<profiles>
		<profile>
			<id>macos</id>
			<activation>
				<os>
					<family>mac</family>
				</os>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>3.6.3</version>
						<executions>
							<execution>
								<id>sign-macos-distro-x86_64</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<executable>${project.basedir}/signing/codesign-macos.sh</executable>
									<workingDirectory>/tmp</workingDirectory>
									<arguments>
										<argument>${project.basedir}</argument>
										<argument>${project.build.directory}/products/com.okworx.ilcd.validation.tool.product/macosx/cocoa/x86_64/ILCDValidationTool.app</argument>
									</arguments>
									<skip>${sign.macos.skip}</skip>
								</configuration>
							</execution>
							<execution>
								<id>sign-macos-distro-aarch64</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<executable>${project.basedir}/signing/codesign-macos.sh</executable>
									<workingDirectory>/tmp</workingDirectory>
									<arguments>
										<argument>${project.basedir}</argument>
										<argument>${project.build.directory}/products/com.okworx.ilcd.validation.tool.product/macosx/cocoa/aarch64/ILCDValidationTool.app</argument>
									</arguments>
									<skip>${sign.macos.skip}</skip>
								</configuration>
							</execution>
							<execution>
								<id>build-dmg_x86_64</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<!-- get & install from https://github.com/create-dmg/create-dmg -->
									<executable>create-dmg</executable>
									<workingDirectory>${project.build.directory}/products</workingDirectory>
									<arguments>
										<argument>--volname</argument>
										<argument>'ILCD Validation Tool'</argument>
										<argument>--volicon</argument>
										<argument>${project.basedir}/resources/icons/ILCDValidator.icns</argument>
										<argument>--background</argument>
										<argument>${project.basedir}/resources/mac/background@2x.png</argument>
										<argument>--window-pos</argument>
										<argument>200</argument>
										<argument>120</argument>
										<argument>--window-size</argument>
										<argument>880</argument>
										<argument>435</argument>
										<argument>--icon-size</argument>
										<argument>80</argument>
										<argument>--add-file</argument>
										<argument>LICENSE.txt</argument>
										<argument>${project.basedir}/resources/legal/LICENSE.txt</argument>
										<argument>750</argument>
										<argument>170</argument>
										<argument>--add-file</argument>
										<argument>licenses</argument>
										<argument>${project.basedir}/resources/legal/licenses</argument>
										<argument>750</argument>
										<argument>290</argument>
										<argument>--add-file</argument>
										<argument>README.txt</argument>
										<argument>${project.basedir}/resources/mac/README.txt</argument>
										<argument>750</argument>
										<argument>50</argument>
										<argument>--app-drop-link</argument>
										<argument>500</argument>
										<argument>160</argument>
										<argument>--icon</argument>
										<argument>ILCDValidationTool.app</argument>
										<argument>200</argument>
										<argument>160</argument>
										<argument>--hide-extension</argument>
										<argument>ILCDValidationTool.app</argument>
										<argument>ILCDValidationTool_${unqualifiedVersion}_${buildDate}-macosx.cocoa.x86_64-Intel.dmg</argument>
										<argument>${project.build.directory}/products/com.okworx.ilcd.validation.tool.product/macosx/cocoa/x86_64</argument>
									</arguments>
									<skip>${dmg.skip}</skip>
								</configuration>
							</execution>
							<execution>
								<id>build-dmg_aarch64</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<!-- get & install from https://github.com/create-dmg/create-dmg -->
									<executable>create-dmg</executable>
									<workingDirectory>${project.build.directory}/products</workingDirectory>
									<arguments>
										<argument>--volname</argument>
										<argument>'ILCD Validation Tool'</argument>
										<argument>--volicon</argument>
										<argument>${project.basedir}/resources/icons/ILCDValidator.icns</argument>
										<argument>--background</argument>
										<argument>${project.basedir}/resources/mac/background@2x.png</argument>
										<argument>--window-pos</argument>
										<argument>200</argument>
										<argument>120</argument>
										<argument>--window-size</argument>
										<argument>880</argument>
										<argument>435</argument>
										<argument>--icon-size</argument>
										<argument>80</argument>
										<argument>--add-file</argument>
										<argument>LICENSE.txt</argument>
										<argument>${project.basedir}/resources/legal/LICENSE.txt</argument>
										<argument>750</argument>
										<argument>170</argument>
										<argument>--add-file</argument>
										<argument>licenses</argument>
										<argument>${project.basedir}/resources/legal/licenses</argument>
										<argument>750</argument>
										<argument>290</argument>
										<argument>--add-file</argument>
										<argument>README.txt</argument>
										<argument>${project.basedir}/resources/mac/README.txt</argument>
										<argument>750</argument>
										<argument>50</argument>
										<argument>--app-drop-link</argument>
										<argument>500</argument>
										<argument>160</argument>
										<argument>--icon</argument>
										<argument>ILCDValidationTool.app</argument>
										<argument>200</argument>
										<argument>160</argument>
										<argument>--hide-extension</argument>
										<argument>ILCDValidationTool.app</argument>
										<argument>ILCDValidationTool_${unqualifiedVersion}_${buildDate}-macosx.cocoa.aarch64-Apple_silicon.dmg</argument>
										<argument>${project.build.directory}/products/com.okworx.ilcd.validation.tool.product/macosx/cocoa/aarch64</argument>
									</arguments>
									<skip>${dmg.skip}</skip>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>build-helper-maven-plugin</artifactId>
						<version>3.6.1</version>
						<executions>
							<execution>
								<id>attach-dmg</id>
								<phase>package</phase>
								<goals>
									<goal>attach-artifact</goal>
								</goals>
								<configuration>
									<artifacts>
										<artifact>
											<file>${project.build.directory}/products/ILCDValidationTool_${unqualifiedVersion}_${buildDate}-macosx.cocoa.x86_64-Intel.dmg</file>
											<type>dmg</type>
											<classifier>x86_64</classifier>
										</artifact>
										<artifact>
											<file>${project.build.directory}/products/ILCDValidationTool_${unqualifiedVersion}_${buildDate}-macosx.cocoa.aarch64-Apple_silicon.dmg</file>
											<type>dmg</type>
											<classifier>aarch64</classifier>
										</artifact>
									</artifacts>
									<skip>${dmg.skip}</skip>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<revisionOnScmFailure>no.scm.config.in.pom</revisionOnScmFailure>
				</configuration>
				<executions>
					<execution>
						<id>create-timestamp-id</id>
						<phase>initialize</phase>
						<goals>
							<goal>create-timestamp</goal>
						</goals>
						<configuration>
							<timestampFormat>yyyyMMdd</timestampFormat>
							<timestampPropertyName>buildDate</timestampPropertyName>
							<!-- formats the timestamp all together like 2016-04-04 14:17:05.123 
								and puts it in the ${buildDate} buildProperty -->
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-director-plugin</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<productRepository>https://download.eclipse.org/justj/jres/25/updates/release/latest/</productRepository>
					<formats>
						<win32>zip</win32>
						<linux>tar.gz</linux>
					</formats>
					<products>
						<product>
							<id>com.okworx.ilcd.validation.tool.product</id>
							<rootFolders>
								<macosx>ILCDValidationTool.app</macosx>
							</rootFolders>
							<archiveFileName>ILCDValidationTool_${unqualifiedVersion}_${buildDate}</archiveFileName>
						</product>
					</products>
					<parallel>true</parallel>
				</configuration>
				<executions>
					<execution>
						<id>materialize-products</id>
						<goals>
							<goal>materialize-products</goal>
						</goals>
					</execution>
					<execution>
						<id>archive-products</id>
						<goals>
							<goal>archive-products</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-repository-plugin</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<includeAllDependencies>true</includeAllDependencies>
					<compress>true</compress>
					<profileProperties>
						<macosx-bundled>true</macosx-bundled>
					</profileProperties>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>3.2.8</version>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
						<configuration>
							<skip>${sign.gpg.skip}</skip>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.codehaus.mojo
										</groupId>
										<artifactId>
											buildnumber-maven-plugin
										</artifactId>
										<versionRange>
											[1.4,)
										</versionRange>
										<goals>
											<goal>
												create-timestamp
											</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.okworx.ilcd.validation</groupId>
			<artifactId>com.okworx.ilcd.validation.tool.plugin</artifactId>
			<version>2.14.0</version>
		</dependency>
	</dependencies>
</project>